# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17I4Yxanb0vjxKRDF71X0DY2PSU_AgfrM
"""

import random
import math
import networkx as nx
import matplotlib.pyplot as plt

NOKTA_SAYISI = 11
AREA_SIZE = 100
SEED = 42
SAVE_IMAGE = True

random.seed(SEED)


noktalar = [(random.uniform(0, AREA_SIZE), random.uniform(0, AREA_SIZE)) for _ in range(NOKTA_SAYISI)]  #nokta sayısı kadar rastgele nokta oluşturdum
G = nx.Graph() #boş bir graf oluşturdum
for i, (x, y) in enumerate(noktalar): #noktalar listesindeki her bir (x, y) koordinatını ve onun 'i' indeksini aldım
    G.add_node(i, pos=(x, y)) #i kimliğiyle bir düğüm oluşturdum ve pos özelliği olarak x,y koordinatlarını atadım

for i in range(NOKTA_SAYISI):
    for j in range(i + 1, NOKTA_SAYISI):
        uzaklik = math.dist(noktalar[i], noktalar[j]) #i ve j düğümlerinin koordinatlarını aldım math.dist fonksiyonu ile oklid uzaklığını hesapladım.
        G.add_edge(i, j, weight=uzaklik) #i dügümü ve j dügümü arasina kenar ekledim

def nearest_neighbor(G, start=0):
    visited = [start] #gezilen
    current = start
    toplam_uzaklik = 0

    while len(visited) < len(G.nodes): #gezilen düğüm sayısı grafikte düğüm sayısından küçük olduğu sürece dönmek için
        neighbors = {n: G[current][n]['weight'] for n in G.nodes if n not in visited} #bulunduğum düğümden daha önce ziyaret etmediğim düğümlerin ağırlıklarını dictionary olarak listeleme
        next_node = min(neighbors, key=neighbors.get) #neighbors.get => sözlükteki değerleri karşılaştırmak için
        toplam_uzaklik += neighbors[next_node] #seçtiğim en yakın komşuya gitmek için gerekli mesafeyi toplam uzaklığa ekle
        visited.append(next_node) #seçtiğim noktayı gezilenler listesine ekle
        current = next_node

    toplam_uzaklik += G[current][start]['weight']
    visited.append(start)
    return visited, toplam_uzaklik


initial_path, nn_distance = nearest_neighbor(G)


pos = nx.get_node_attributes(G, 'pos')
plt.figure(figsize=(9, 7))

nx.draw(G, pos, with_labels=True, node_color='purple', node_size=500, font_size=10)

nn_edges = list(zip(initial_path, initial_path[1:]))
nx.draw_networkx_edges(G, pos, edgelist=nn_edges, edge_color='lightblue', style='dashed', width=2, label='Nearest Neighbor')

plt.title(f"TSP Solution (Nearest Neighbor Only)\nToplam Mesafe = {nn_distance:.2f}", fontsize=12)
plt.legend()
plt.axis("equal")

if SAVE_IMAGE:
    plt.savefig("odev1.png", dpi=300)
plt.show()

print("Nearest Neighbor Path:", initial_path)
print(f"Nearest Neighbor Distance: {nn_distance:.2f}")