# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10R55t150p3cW3ct3_7WguSKE0wOtc7OK
"""

pip install osmnx folium

import osmnx as ox
import networkx as nx
import folium
import random
import math
from google.colab import files


NOKTA_SAYISI = 11
SEED = 42
SAVE_FILE = "odev2.html"
random.seed(SEED)


PLACE_NAME = "Muratpaşa, Antalya, Turkey"

ox.settings.use_cache=True #indirilen harita verileni ön bellekte tutmak için
ox.settings.log_console=True



def nearest_neighbor(G, start=0):
    visited = [start]
    current = start
    toplam_uzaklik = 0

    while len(visited) < len(G.nodes):
        neighbors = {n: G[current][n]['weight'] for n in G.nodes if n not in visited and G.has_edge(current, n)}

        if not neighbors:
            break

        next_node = min(neighbors, key=neighbors.get)

        if neighbors[next_node] == float('inf'):
            break

        toplam_uzaklik += neighbors[next_node]
        visited.append(next_node)
        current = next_node

    if G.has_edge(current, start):
        donus_mesafesi = G[current][start]['weight']
        if donus_mesafesi != float('inf'):
            toplam_uzaklik += donus_mesafesi
            visited.append(start)

    return visited, toplam_uzaklik



def calculate_path_distance(path, G):

    distance = 0
    for i in range(len(path) - 1):
        if G.has_edge(path[i], path[i+1]):
            weight = G[path[i]][path[i+1]]['weight']
            if weight != float('inf'):
                distance += weight
            else:
                # Ulaşılamayan bir yol varsa mesafeyi sonsuz yapmak için
                return float('inf')
        else:
            return float('inf')
    return distance

def two_opt(G, current_path):
    #Verilen bir rotayı 2-opt algoritması ile iyileştirme

    best_path = current_path[:]#current pathin kopyasını alırız
    best_distance = calculate_path_distance(best_path, G)#başlangıç rotasının mesafesini hesaplama

    if best_distance == float('inf'):
         print("  Uyarı: Başlangıç rotası geçersiz, 2-Opt çalıştırılamadı.")
         return current_path, -1

    n = len(best_path) - 1 # düğüm sayısını doğru hesaplamak için sondaki başlangıç düğümünü saymayız

    improved = True
    iteration = 0
    while improved:
        iteration += 1
        improved = False

        for i in range(1, n - 2):
            for k in range(i + 1, n):
                # İki kenarı değiştiriyoruz: (i-1, i) ve (k, k+1)
                # A = best_path[i-1], B = best_path[i]
                # C = best_path[k],   D = best_path[k+1]

                try:
                    # Mevcut mesafe
                    original_dist = G[best_path[i-1]][best_path[i]]['weight'] + G[best_path[k]][best_path[k+1]]['weight']

                    # Yeni  mesafe
                    new_dist = G[best_path[i-1]][best_path[k]]['weight'] + G[best_path[i]][best_path[k+1]]['weight']

                    # Eğer yeni mesafe daha kısaysa ve ulaşılabiliyorsa
                    if new_dist < original_dist:

                        # i ve k arasındaki segmenti ters çevir (slice [i:k+1])
                        best_path[i:k+1] = best_path[i:k+1][::-1]

                        # best_distance'i güncelle
                        best_distance = best_distance - original_dist + new_dist
                        improved = True


                        break
                except (KeyError, nx.NetworkXNoPath):

                    continue

            if improved:
                break

    print(f"  2-Opt {iteration} iterasyonda tamamlandı.")
    return best_path, best_distance


G_map = ox.graph_from_place(PLACE_NAME, network_type="drive")




all_node_ids = list(G_map.nodes())#tüm kavşakların idsini listeler
tsp_node_ids = random.sample(all_node_ids, NOKTA_SAYISI)#bu kavşaklardan nokta sayısı kadar rastgele nokta seçer



G_tsp = nx.Graph() #boş bir graf oluştururum
for i in range(NOKTA_SAYISI): #nokta sayısına kadar
    G_tsp.add_node(i) #grafa yeni bir düğüm eklerim

for i in range(NOKTA_SAYISI):
    for j in range(i + 1, NOKTA_SAYISI):  #tüm düğüm çiftlerini gezmek için
        source_node_osm = tsp_node_ids[i]#başlangıç düğümü idsi
        target_node_osm = tsp_node_ids[j]#hedef düğüm idsi
        try:
            mesafe = nx.shortest_path_length(G_map, source_node_osm, target_node_osm, weight="length") #haritayı kullanarak bu iki nokta arasındaki en kısa yolu bul ve bunu uzaklığa göre hesapla
            G_tsp.add_edge(i, j, weight=mesafe)
        except nx.NetworkXNoPath:
            G_tsp.add_edge(i, j, weight=float('inf'))




print("4. Adım: TSP çözülüyor (Nearest Neighbor Heuristic uygulanıyor)...")
yol_indeksleri, nn_distance = nearest_neighbor(G_tsp, start=0)#G_tspde seçili düğümleri 0dan başlayarak en yakın komşu yöntemiyle hesapla toplam uzaklığı nn_distance gidilen indeksleri de yol_indeksleri değişkenine ata
print(f"  Nearest Neighbor Sonucu: {nn_distance / 1000:.2f} km")
print(f"  Nearest Neighbor Rotası: {yol_indeksleri}")


if nn_distance == float('inf') or not yol_indeksleri or len(yol_indeksleri) < 4:
     print("  Geçersiz veya çok kısa NN rotası, 2-Opt atlanıyor.")
     iyilestirilmis_indeksler = yol_indeksleri
     iyilestirilmis_uzaklık = nn_distance
else:
     iyilestirilmis_indeksler, iyilestirilmis_uzaklık = two_opt(G_tsp, yol_indeksleri)
     print(f"  2-Opt Sonrası Sonuç: {iyilestirilmis_uzaklık / 1000:.2f} km")
     print(f"  2-Opt Rotası : {iyilestirilmis_indeksler}")



try:
    final_osm_path = [tsp_node_ids[i] for i in iyilestirilmis_indeksler]
except (IndexError, TypeError):
    print("Hata: Path indeksleri OSM ID'leri ile eşleştirilemedi.")
    final_osm_path = []


if final_osm_path:
    start_node_data = G_map.nodes[final_osm_path[0]]
    map_center = (start_node_data['y'], start_node_data['x'])
else:

    map_center = [36.8916, 30.7650]

m = folium.Map(location=map_center, zoom_start=13)

# Tüm 11 TSP düğümünü haritaya ekleme
for i, node_id in enumerate(tsp_node_ids):
    node_data = G_map.nodes[node_id]
    folium.Marker(
        location=[node_data['y'], node_data['x']],
        popup=f"Nokta {i}",
        tooltip=f"OSM ID: {node_id}",
        icon=folium.Icon(color='red')
    ).add_to(m)

# Başlangıç noktası ayarları
start_node_data = G_map.nodes[tsp_node_ids[0]]
folium.Marker(
    location=[start_node_data['y'], start_node_data['x']],
    popup="Başlangıç Noktası (0)",
    tooltip=f"OSM ID: {tsp_node_ids[0]}",
    icon=folium.Icon(color='green', icon='play')
).add_to(m)

# İyileştirilmiş rotayı haritaya çiz
if final_osm_path:
    for i in range(len(final_osm_path) - 1):
        node_1_id = final_osm_path[i]
        node_2_id = final_osm_path[i+1]

        try:
            route_nodes_osm = nx.shortest_path(G_map, node_1_id, node_2_id, weight='length')
            route_coords = [(G_map.nodes[n]['y'], G_map.nodes[n]['x']) for n in route_nodes_osm]

            folium.PolyLine(
                route_coords,
                color='blue',
                weight=5,
                opacity=0.7,
                tooltip=f"Adım {i+1}: {iyilestirilmis_indeksler[i]} -> {iyilestirilmis_indeksler[i+1]}"
            ).add_to(m)

        except nx.NetworkXNoPath:
             print(f"  Görselleştirme Uyarısı: {node_1_id} ve {node_2_id} arası rota çizilemedi (yol yok).")



m.save(SAVE_FILE)


print(f"Seçilen Lokasyon: {PLACE_NAME}")
print(f"\nNearest Neighbor Rotası: \n{yol_indeksleri}")
print(f"NN Toplam Mesafe: {nn_distance / 1000:.2f} km")

print(f"\n2-Opt İyileştirilmiş Rota: \n{iyilestirilmis_indeksler}")
print(f"2-Opt Toplam Mesafe: {iyilestirilmis_uzaklık / 1000:.2f} km")

files.download(SAVE_FILE)

from google.colab import drive
drive.mount('/content/drive')